---

- name: ensure etherpad packages are installed
  apt:
    pkg: "{{ etherpad_console_packages if ansible_distribution_major_version|int > 8 else etherpad_console_packages_php5 }}"
    state: present

- name: ensure etherpad-lite-console is present
  git:
    repo: https://github.com/0x46616c6b/etherpad-lite-console
    dest: "{{ etherpad_console_path }}"
    version: "{{ etherpad_console_path_version }}"
  become: true
  become_user: "{{ etherpad_user }}"

- name: Run composer install
  composer:
    command: install
    working_dir: "{{ etherpad_console_path }}"

- name: ensure purge cronjob file is latest
  template:
    src: etc/cron.d/etherpad-lite-console.j2
    dest: /etc/cron.d/etherpad-lite-console
    owner: root
    group: root
    mode: 0644
  when: etherpad_console_purge_enabled
