---

- name: ensure apt_preferences include file for deb.nodesource.com is present
  copy:
    src: apt/preferences.d/deb.nodesource.com.pref
    dest: /etc/apt/preferences.d/deb.nodesource.com.pref
    mode: 0644
    owner: root
    group: root

- name: ensure etherpad user is present
  user:
    name: "{{ etherpad_user }}"
    home: "{{ etherpad_home }}"
    shell: "/bin/bash"
    state: present

- name: ensure ssh key file are latest
  copy:
    src: "{{ etherpad_repository_key_file_src }}"
    dest: "{{ etherpad_repository_key_file }}"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_user }}"
    mode: "0600"
  when:
    - etherpad_repository_key_file_src|length > 0

- name: ensure required packages are installed
  apt:
    pkg: "{{ etherpad_required_packages }}"
    state: present

- name: ensure etherpad is latest
  git:
    repo: "{{ etherpad_repository }}"
    dest: "{{ etherpad_path }}"
    version: "{{ etherpad_repository_version }}"
    key_file: "{{ etherpad_repository_key_file }}"
    depth: 1
  become: true
  become_user: "{{ etherpad_user }}"
  notify: ensure etherpad dependencies are latest

- name: ensure etherpad config is latest
  template:
    src: settings.json.j2
    dest: "{{ etherpad_path }}/settings.json"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    mode: 0644
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite

- include: redis.yml
  when: etherpad_db_type == "redis"

- include: mysql.yml
  when: etherpad_db_type == "mysql"

- name: ensure etherpad systemd unit is latest
  template:
    src: etc/systemd/system/etherpad-lite.service.j2
    dest: /etc/systemd/system/etherpad-lite.service
    owner: root
    group: root
    mode: 0644

- name: ensure etherpad will start after system is booted
  service:
    name: etherpad-lite
    enabled: yes

- name: ensure etherpad api key is latest
  template:
    src: APIKEY.txt.j2
    dest: "{{ etherpad_path }}/APIKEY.txt"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    mode: 0640
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite

- name: flush handlers
  meta: flush_handlers

- name: install etherpad plugins
  npm:
    name: "{{ item }}"
    path: "{{ etherpad_path }}"
    state: "{{ etherpad_plugins_state }}"
    registry: https://github.com
  become: true
  become_user: "{{ etherpad_user }}"
  with_items: "{{ etherpad_plugins|d() }}"
  notify:
    - ensure etherpad dependencies are latest
    - restart etherpad-lite

- name: copy custom logo file if configured
  copy:
    src: "{{ etherpad_custom_logo_src }}"
    dest: "{{ etherpad_path }}/src/static/"
    owner: "{{ etherpad_user }}"
    group: "{{ etherpad_group }}"
    mode: 0644
  when: etherpad_custom_logo_src

- include: abiword.yml
  when: etherpad_abiword_enabled
