---
- name: restart etherpad-lite
  service:
    name: etherpad-lite
    state: restarted

- name: ensure etherpad dependencies are latest
  command: bin/installDeps.sh
  args:
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  notify: fix package-lock.json  # this is a hack

- name: fix package-lock.json  # noqa 303
  command: git checkout src/package-lock.json
  args:
    chdir: "{{ etherpad_path }}"
  become: true
  become_user: "{{ etherpad_user }}"
  notify: restart etherpad-lite

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
